<a href="https://colab.research.google.com/github/hsallrounder/Introduction-to-Machine-Learning-Lab/blob/master/LAB_M3_16_11_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/Datasets/Melbourne_housing_FULL.csv')

In [ ]:
df1

           Suburb             Address  ...             Regionname Propertycount
0      Abbotsford       68 Studley St  ...  Northern Metropolitan        4019.0
1      Abbotsford        85 Turner St  ...  Northern Metropolitan        4019.0
2      Abbotsford     25 Bloomburg St  ...  Northern Metropolitan        4019.0
3      Abbotsford  18/659 Victoria St  ...  Northern Metropolitan        4019.0
4      Abbotsford        5 Charles St  ...  Northern Metropolitan        4019.0
...           ...                 ...  ...                    ...           ...
34852  Yarraville         13 Burns St  ...   Western Metropolitan        6543.0
34853  Yarraville       29A Murray St  ...   Western Metropolitan        6543.0
34854  Yarraville      147A Severn St  ...   Western Metropolitan        6543.0
34855  Yarraville    12/37 Stephen St  ...   Western Metropolitan        6543.0
34856  Yarraville    3 Tarrengower St  ...   Western Metropolitan        6543.0

[34857 rows x 21 columns]

In [ ]:
col_to_fill=['Suburb', 	'Address',	'Rooms',	'Type', 'Price',	'Method',	'SellerG',	'Date',	'Distance',	'Postcode', 	'Bedroom2',	'Bathroom',	'Car',	'Landsize', 'BuildingArea',	'YearBuilt',	'CouncilArea',	'Lattitude',	'Longtitude',	'Regionname',	'Propertycount']

In [ ]:
df1.isna().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        3
dtype: int64

In [ ]:
df1[col_to_fill]=df1[col_to_fill].fillna(0);
df1.isna().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
CouncilArea      0
Lattitude        0
Longtitude       0
Regionname       0
Propertycount    0
dtype: int64

In [ ]:
df1 = df1.drop(['Address','Date','Postcode','Longtitude','Lattitude','YearBuilt'],axis=1)

In [ ]:
df2 = pd.get_dummies(df1)
df2

       Rooms  ...  Regionname_Western Victoria
0          2  ...                            0
1          2  ...                            0
2          2  ...                            0
3          3  ...                            0
4          3  ...                            0
...      ...  ...                          ...
34852      4  ...                            0
34853      2  ...                            0
34854      2  ...                            0
34855      3  ...                            0
34856      2  ...                            0

[34857 rows x 803 columns]

In [ ]:
y=df2['Price']
X=df2.drop(['Price'],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=40)

In [ ]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression().fit(X_train,y_train)
print(LR.score(X_train,y_train))
print(LR.score(X_test,y_test))

0.33466972616007684
-5205155165.493948

In [ ]:
from sklearn.linear_model import Lasso
lasso =Lasso(alpha=0.1,tol=20)
lasso.fit(X_train,y_train)
print(lasso.score(X_train,y_train))
print(lasso.score(X_test,y_test))

0.31517399627779796
0.2607657581320785

In [ ]:
from sklearn.linear_model import Ridge
Rg = Ridge(alpha=0.1,tol=20)
Rg.fit(X_train,y_train)
print(Rg.score(X_train,y_train))
print(Rg.score(X_test,y_test))

0.33464553056974045
0.2789872884292368